---
title: "STATS 571 Final Project"
author: "Lindsey Lin, Shirley Toribio"
format: pdf
editor: visual
---

```{r}
library(haven)
library(tidyverse)
library(forcats)
library(sandwich)
library(lmtest)
library(boot)
```

### Data cleaning

```{r}
wls <- read_dta("wls_subset.dta")
```

```{r}
wls_1 <- wls %>% 
  filter(edyr64 > 0) %>%          # keep non-negative years of schooling
  filter(!is.na(yrer74i1)) %>%    # remove missing earnings
  filter(yrer74i1 >= 0)           # keep non-negative earnings

wls_2 <- wls_1 %>% 
  mutate(colgrad = as.integer(edyr64 >= 16), # treatment: college graduate or not
         eduyears = edyr64) %>%      
  
  rename(sex = sexrsp,
         hs_type = hsdm57,
         hs_rank = hsrscorq,
         hs_opinion = hsntrstq,
         hs_size = hssize,
         hs_col_prep = colprepq,
         hs_merit = nameritq,
         hs_col_exam = cebexamq,
         parent_op_col = parencq,
         dad_edu = edfa57q,
         mom_edu = edmo57q,
         family_income57 = pi5760,
         dad_farmer = ocf357)

wls_clean <- wls_2 %>% 
  # -1 means "don't know", -3 means "refused"
  mutate(hs_rank = na_if(hs_rank, -3),
         hs_opinion = na_if(hs_opinion, -3),
         hs_merit = na_if(hs_merit, -3),
         hs_col_exam = na_if(hs_col_exam, -3),
         hs_col_prep = na_if(hs_col_prep, -3),
         dad_edu = na_if(dad_edu, -3),
         dad_edu = na_if(dad_edu, -1),
         mom_edu = na_if(mom_edu, -3),
         mom_edu = na_if(mom_edu, -1),
         family_income57 = na_if(family_income57, -3)) %>% 
  
  # log_transform earnings
  mutate(income74 = yrer74i1 * 100,
         family_income57 = family_income57 * 100,
         log_income74 = log(income74 + 1),
         log_family_income57 = log(family_income57 + 1)) %>% 
  
  mutate(sex = recode(as.character(sex), 
                      "1" = "Male", 
                      "2" = "Female"),
         hs_type = recode(as.character(hs_type), 
                          "1" = "Catholic",
                          "2" = "Private-Other",
                          "3" = "Public"),
         hs_opinion = recode(as.character(hs_opinion),
                             "1" = "Positive",
                             "2" = "Negative",
                             "3" = "Indifferent"),
         hs_merit = recode(as.character(hs_merit),
                           "1" = "Yes",
                           "2" = "No"),
         hs_col_exam = recode(as.character(hs_col_exam),
                              "1" = "Yes",
                              "2" = "No"),
         hs_col_prep = recode(as.character(hs_col_prep),
                              "1" = "Yes",
                              "2" = "No"),
         parent_op_col = recode(as.character(parent_op_col),
                                "1" = "YesCollege",
                                "2" = "NoCollege",
                                "3" = "DontCare",
                                "4" = "StrongNoCollege",
                                .default = NA_character_),
         dad_farmer = recode(as.character(dad_farmer),
                             "1" = "No",
                             "2" = "Yes",
                             "3" = "Yes",
                             "4" = "Yes",
                             "5" = "Yes")) %>% 
  
  mutate(colgrad = factor(colgrad, levels = c(0, 1), labels = c("No", "Yes")),
         sex = factor(sex),
         hs_type = factor(hs_type),
         hs_opinion = factor(hs_opinion),
         hs_merit = factor(hs_merit),
         hs_col_exam = factor(hs_col_exam),
         hs_col_prep = factor(hs_col_prep),
         parent_op_col = factor(parent_op_col),
         dad_farmer = factor(dad_farmer)) %>% 
  
  mutate(parent_op_col_simple = case_when(parent_op_col == "YesCollege" ~ "SupportCollege",
                                   parent_op_col == "NoCollege" ~ "AgainstCollege",
                                   parent_op_col == "StrongNoCollege" ~ "AgainstCollege",
                                   parent_op_col == "DontCare" ~ "Neutral",
                                   TRUE ~ NA_character_),
         parent_op_col_simple = factor(parent_op_col_simple))
```

Check missingness for `wls_clean`.

```{r}
sort(sapply(wls_clean, function(x) sum(is.na(x))), decreasing = TRUE)
```

Analysis dataset for main causal models, use complete cases on the core variables.

```{r}
wls_analysis <- wls_clean %>% 
  select(idpub, colgrad, eduyears, income74, log_income74, sex, 
         hs_rank, hs_size, hs_type, hs_merit, hs_col_prep, hs_col_exam,
         dad_edu, mom_edu, dad_farmer, parent_op_col_simple, 
         family_income57, log_family_income57, ) %>% 
  drop_na(colgrad, log_income74, log_family_income57, sex, hs_rank, dad_edu, mom_edu)

# standardized versions of continuous covariates
wls_analysis <- wls_analysis %>% 
  mutate(hs_rank_z = as.numeric(scale(hs_rank)),
         hs_size_z = as.numeric(scale(hs_size)),
         dad_edu_z = as.numeric(scale(dad_edu)),
         mom_edu_z = as.numeric(scale(mom_edu)),
         log_family_income57_z = as.numeric(scale(log_family_income57)))
```

### Outcome regression

Baseline model `m0`

```{r}
m0 <- lm(log_income74 ~ colgrad, data = wls_analysis)
summary(m0)
```

```{r}
m1 <- lm(log_income74 ~ colgrad + hs_rank + dad_edu + mom_edu +
           log_family_income57 + sex,
         data = wls_analysis)
summary(m1)
```

```{r}
beta <- coef(m1)["colgradYes"]
100 * (exp(beta) - 1)
```

```{r}
par(mfrow = c(2,2))
plot(m1)
```

```{r}
coeftest(m1, vcov = vcovHC(m1, type = "HC1"))
```

```{r}
m2 <- lm(log_income74 ~ colgrad + 
           hs_rank + I(hs_rank^2) +
           dad_edu + mom_edu +
           log_family_income57 + sex,
         data = wls_analysis)

coeftest(m2, vcov = vcovHC(m2, type = "HC1"))
```

```{r}
m3 <- lm(log_income74 ~ colgrad +
           hs_rank + dad_edu + mom_edu +
           log_family_income57 + sex +
           hs_col_exam + hs_col_prep + hs_merit,
         data = wls_analysis)

coeftest(m3, vcov = vcovHC(m3, type = "HC1"))
```

```{r}
wls_analysis %>%
  group_by(colgrad) %>%
  summarise(
    hs_rank = mean(hs_rank, na.rm = TRUE),
    dad_edu = mean(dad_edu, na.rm = TRUE),
    mom_edu = mean(mom_edu, na.rm = TRUE),
    log_income = mean(log_income74, na.rm = TRUE)
  )
```

```{r}
# Predict counterfactuals
yhat1 <- predict(m1, newdata = transform(wls_analysis, colgrad = "Yes"))
yhat0 <- predict(m1, newdata = transform(wls_analysis, colgrad = "No"))

# ATE estimate
mean(yhat1 - yhat0)
```

```{r}
# function to compute ATE
ate_fn <- function(data, indices) {
  d <- data[indices, ]
  
  m <- lm(log_income74 ~ colgrad + hs_rank + dad_edu + mom_edu +
            log_family_income57 + sex, data = d)
  
  y1 <- predict(m, newdata = transform(d, colgrad = "Yes"))
  y0 <- predict(m, newdata = transform(d, colgrad = "No"))
  
  return(mean(y1 - y0))
}

# bootstrap
set.seed(123)
boot_res <- boot(wls_analysis, ate_fn, R = 500)

# standard error
sd(boot_res$t)

# 95% CI
quantile(boot_res$t, c(0.025, 0.975))
```

### **Heterogeneous Treatment Effects**

Effect varies by ability

```{r}
m_ht <- lm(log_income74 ~ colgrad * hs_rank +
             dad_edu + mom_edu + log_family_income57 + sex,
           data = wls_analysis)

coeftest(m_ht, vcov = vcovHC(m_ht, type = "HC1"))
```

```{r}
m_ht2 <- lm(log_income74 ~ colgrad * dad_edu + colgrad * mom_edu +
              hs_rank + log_family_income57 + sex,
            data = wls_analysis)

coeftest(m_ht2, vcov = vcovHC(m_ht2, type = "HC1"))
```

```{r}
# split by high vs low parental education
median_dad <- median(wls_analysis$dad_edu, na.rm = TRUE)

low <- subset(wls_analysis, dad_edu <= median_dad)
high <- subset(wls_analysis, dad_edu > median_dad)

lm(log_income74 ~ colgrad + hs_rank + dad_edu + mom_edu +
     log_family_income57 + sex, data = low)

lm(log_income74 ~ colgrad + hs_rank + dad_edu + mom_edu +
     log_family_income57 + sex, data = high)
```

```{r}
library(modelsummary)

modelsummary(
  list(
    "Baseline (m1)" = m1,
    "Nonlinear (m2)" = m2,
    "Extended (m3)" = m3
  ),
  vcov = list(
    vcovHC(m1, type = "HC1"),
    vcovHC(m2, type = "HC1"),
    vcovHC(m3, type = "HC1")
  ),
  stars = TRUE
)
```

```{r}
wls_analysis %>%
  group_by(sex) %>%
  summarise(
    mean_income = mean(income74, na.rm = TRUE),
    median_income = median(income74, na.rm = TRUE),
    mean_log_income = mean(log_income74, na.rm = TRUE),
    pct_zero_income = mean(income74 == 0, na.rm = TRUE)
  )
```

```{r}
table(wls_analysis$sex, wls_analysis$income74 == 0)
```
